# Generated by Django 4.2.7 on 2023-11-08 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id_adopcion', models.AutoField(db_column='Id_adopcion', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Adopcion',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(db_column='Id_contacto', primary_key=True, serialize=False)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(db_column='Id_direccion', primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, db_column='Calle', max_length=255, null=True)),
                ('num_ext', models.CharField(blank=True, db_column='Num_ext', max_length=10, null=True)),
                ('num_int', models.CharField(blank=True, db_column='Num_int', max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, db_column='Colonia', max_length=255, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Direccion',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.AutoField(db_column='Id_especie', primary_key=True, serialize=False)),
                ('nombre_comun', models.CharField(blank=True, db_column='Nombre_comun', max_length=255, null=True)),
                ('nombre_cientifico', models.CharField(blank=True, db_column='Nombre_cientifico', max_length=255, null=True)),
                ('descripcion_especie', models.TextField(blank=True, db_column='Descripcion_especie', null=True)),
            ],
            options={
                'db_table': 'Especie',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(db_column='Id_persona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('apellido_p', models.CharField(blank=True, db_column='Apellido_p', max_length=100, null=True)),
                ('apellido_m', models.CharField(blank=True, db_column='Apellido_m', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.AutoField(db_column='Id_puesto', primary_key=True, serialize=False)),
                ('nombre_puesto', models.CharField(blank=True, db_column='Nombre_puesto', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Puesto',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(db_column='Id_seguimiento', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('detalles', models.TextField(blank=True, db_column='Detalles', null=True)),
                ('id_adopcion', models.ForeignKey(blank=True, db_column='Id_adopcion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.adopcion')),
            ],
            options={
                'db_table': 'Seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(db_column='Id_empleado', primary_key=True, serialize=False)),
                ('id_contacto', models.ForeignKey(blank=True, db_column='Id_contacto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.contacto')),
                ('id_direccion', models.ForeignKey(blank=True, db_column='Id_direccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.direccion')),
                ('id_persona', models.ForeignKey(blank=True, db_column='Id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.persona')),
                ('id_puesto', models.ForeignKey(blank=True, db_column='Id_puesto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.puesto')),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(db_column='Id_animal', primary_key=True, serialize=False)),
                ('nombre_animal', models.CharField(blank=True, db_column='Nombre_animal', max_length=100, null=True)),
                ('descripcion_animal', models.TextField(blank=True, db_column='Descripcion_animal', null=True)),
                ('id_especie', models.ForeignKey(blank=True, db_column='Id_especie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.especie')),
            ],
            options={
                'db_table': 'Animal',
            },
        ),
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id_adoptante', models.AutoField(db_column='Id_adoptante', primary_key=True, serialize=False)),
                ('id_contacto', models.ForeignKey(blank=True, db_column='Id_contacto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.contacto')),
                ('id_direccion', models.ForeignKey(blank=True, db_column='Id_direccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.direccion')),
                ('id_persona', models.ForeignKey(blank=True, db_column='Id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.persona')),
            ],
            options={
                'db_table': 'Adoptante',
            },
        ),
        migrations.AddField(
            model_name='adopcion',
            name='id_adoptante',
            field=models.ForeignKey(blank=True, db_column='Id_adoptante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.adoptante'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='id_animal',
            field=models.ForeignKey(blank=True, db_column='Id_animal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.animal'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='Id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.empleado'),
        ),
    ]
