# Generated by Django 4.2.7 on 2023-12-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='id_adoptante',
            field=models.ForeignKey(blank=True, db_column='Id_adoptante', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.adoptante'),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='id_animal',
            field=models.ForeignKey(blank=True, db_column='Id_animal', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.animal'),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='Id_empleado', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.empleado'),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='id_contacto',
            field=models.ForeignKey(blank=True, db_column='Id_contacto', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.contacto'),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='id_direccion',
            field=models.ForeignKey(blank=True, db_column='Id_direccion', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.direccion'),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='id_persona',
            field=models.ForeignKey(blank=True, db_column='Id_persona', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.persona'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id_especie',
            field=models.ForeignKey(blank=True, db_column='Id_especie', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.especie'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_contacto',
            field=models.ForeignKey(blank=True, db_column='Id_contacto', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.contacto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_direccion',
            field=models.ForeignKey(blank=True, db_column='Id_direccion', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.direccion'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_persona',
            field=models.ForeignKey(blank=True, db_column='Id_persona', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.persona'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_puesto',
            field=models.ForeignKey(blank=True, db_column='Id_puesto', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.puesto'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='id_adopcion',
            field=models.ForeignKey(blank=True, db_column='Id_adopcion', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.adopcion'),
        ),
    ]
